<?php

namespace Nimbus\ApartmentsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends EntityRepository
{
  public function getAllActive()
  {
      return $this->getEntityManager()
          ->createQuery(
            'SELECT a FROM NimbusApartmentsBundle:Apartment a 
              JOIN a.owner u
              JOIN a.lease l
              WHERE u.enabled = 1'
            )
          ->getResult();
  }
  
  
  
  public function getBySlug($slug)
  {
    $result =  
      $this->createQueryBuilder('apartment')
        ->select('apartment, lease')
        ->join('apartment.owner', 'owner')
        ->join('apartment.lease', 'lease')
        ->where('owner.enabled = 1')
        ->andWhere('apartment.slug = :slug')
        ->setParameter('slug', $slug)
        ->setMaxResults(1)
        ->getQuery()
        ->execute();

    return count($result)?$result[0]:null;
  }
}