<?php

namespace Nimbus\ApartmentsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentRepository extends EntityRepository
{
//  public function findOneByTitle($title)
//  {
//      return $this->getEntityManager()
//          ->createQuery('SELECT a FROM NimbusApartmentsBundle:Apartment a WHERE a.title = :title')
//          ->setParameter('title', $title)
//          ->getResult();
//  }
}