imports:
    - { resource: "@NimbusApartmentsBundle/Resources/config/security.yml" }

security:
    acl:
        connection: default
        
    encoders:
        'FOS\UserBundle\Model\UserInterface': sha512


    providers:
        fos_userbundle:
            id: fos_user.user_manager