imports:
    - { resource: services.yml }

fos_user:
    user_class: Nimbus\ApartmentsBundle\Entity\User
    registration:
        form:
            handler: apartments.user_registration_handler
            
            
twig:
    form:
        resources:  
           - 'NimbusApartmentsBundle:Form:fields.html.twig'