 
index_browsing:
  pattern: /
  defaults: { _controller: NimbusApartmentsBundle:Browsing:index }
  requirements:
    _method: GET
    
summary_browsing:
  pattern: /summary/{slug}
  defaults: { _controller: NimbusApartmentsBundle:Browsing:summary, _format: json }
  requirements:
    _method: GET
    
details_browsing:
  pattern: /details/{slug}
  defaults: { _controller: NimbusApartmentsBundle:Browsing:details }
  requirements:
    _method: GET
    
    
    
new_apartment:
  pattern: /apartment/new
  defaults: { _controller: NimbusApartmentsBundle:Apartment:new }
    
    
update_apartment:
  pattern: /apartment/update/{slug}
  defaults: { _controller: NimbusApartmentsBundle:Apartment:update }
    
list_apartment:
  pattern: /apartment/list
  defaults: { _controller: NimbusApartmentsBundle:Apartment:list }
    
    
    
delete_apartment:
  pattern: /apartment/delete
  defaults: { _controller: NimbusApartmentsBundle:Apartment:delete }
  requirements:
    _method: POST
    
    
    