NimbusApartmentsBundle_listing:
  pattern: /
  defaults: { _controller: NimbusApartmentsBundle:Listing:index }
  requirements:
    _method: GET
    
    
NimbusApartmentsBundle_registerApartment:
  pattern: /apartment/register
  defaults: { _controller: NimbusApartmentsBundle:Apartment:register, _format: json }
  requirements:
    _method: POST