NimbusApartmentsBundle_listing:
  pattern: /
  defaults: { _controller: NimbusApartmentsBundle:Listing:index }
  requirements:
    _method: GET
    
    
NimbusApartmentsBundle_newApartment:
  pattern: /apartment/new
  defaults: { _controller: NimbusApartmentsBundle:Apartment:new, _format: json }
  requirements:
    _method: POST