security:

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            
    role_hierarchy:
        ROLE_LANDLORD:    ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_LANDLORD]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_LANDLORD, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
        
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        
        - { path: ^/apartment/update, role: ROLE_LANDLORD }
        - { path: ^/apartment/delete, role: ROLE_LANDLORD }