
services:
  
    apartments.apartment_registration_handler:
        class:        'Nimbus\ApartmentsBundle\Handler\ApartmentHandler'
        arguments:    ['@doctrine.orm.entity_manager', '@security.context', '@security.acl.provider', "@request"]
        tags:
            - { name: kernel.event_listener, event: fos_user.user_registered, method: onUserRegistered }
        scope:        request
        
        
    apartments.user_registration_handler:
        class:        'Nimbus\ApartmentsBundle\Handler\RegistrationHandler'
        arguments:    ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@event_dispatcher"]
        scope:        request
        public:       false